#!/bin/bash

echo "🔧 Update EMAIL_FROM to Match Verified Sender"
echo "=============================================="
echo ""
echo "Current EMAIL_FROM: LegitEvents <noreply@legitevents.com>"
echo ""
echo "❌ This email address is not verified in SendGrid"
echo ""
echo "🔧 To fix this:"
echo "1. Check what email address you verified in SendGrid"
echo "2. Update your .env file to match exactly"
echo ""
echo "📝 Example updates:"
echo "   EMAIL_FROM=LegitEvents <your-email@gmail.com>"
echo "   EMAIL_FROM=LegitEvents <your-email@yourdomain.com>"
echo ""
echo "⚠️  Important:"
echo "- The email must be exactly what you verified in SendGrid"
echo "- Include the 'LegitEvents' display name"
echo "- Use angle brackets around the email address"
echo ""
echo "🧪 After updating, test with:"
echo "node test-verified-sendgrid.js"
