#!/bin/bash

echo "🔧 SendGrid Sender Email Verification Required"
echo "=============================================="
echo ""
echo "✅ SendGrid API Key is working correctly!"
echo "❌ Sender email address needs to be verified"
echo ""
echo "📧 Current EMAIL_FROM: LegitEvents <noreply@legitevents.com>"
echo ""
echo "🔧 To fix this issue:"
echo "1. Go to https://app.sendgrid.com"
echo "2. Navigate to Settings → Sender Authentication"
echo "3. Choose 'Single Sender Verification'"
echo "4. Add your email address (e.g., your-email@gmail.com)"
echo "5. Check your email and click the verification link"
echo "6. Update your .env file with the verified email:"
echo ""
echo "   EMAIL_FROM=LegitEvents <your-verified-email@gmail.com>"
echo ""
echo "⚠️  Important:"
echo "- Use a real email address you own"
echo "- The email must be verified in SendGrid"
echo "- You can use your personal Gmail or any email you own"
echo ""
echo "🧪 After verification, test with:"
echo "node test-sendgrid-config.js"
echo ""
echo "📧 Once verified, forgot password emails will be delivered!"
